# Generated by Django 2.2.4 on 2019-08-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('text', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wordList', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fridgedoor.WordList')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Magnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('xpos', models.FloatField()),
                ('ypos', models.FloatField()),
                ('zpos', models.SmallIntegerField()),
                ('door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fridgedoor.Door')),
            ],
            options={
                'ordering': ['zpos'],
            },
        ),
    ]
