# Generated by Django 2.2.4 on 2019-08-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridgedoor', '0002_auto_20190815_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnet',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridgedoor.Door'),
        ),
        migrations.AlterField(
            model_name='word',
            name='wordList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridgedoor.WordList'),
        ),
    ]
