# Generated by Django 2.2.4 on 2019-08-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridgedoor', '0003_auto_20190815_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='wordList',
        ),
        migrations.AddField(
            model_name='word',
            name='wordList',
            field=models.ManyToManyField(to='fridgedoor.WordList'),
        ),
    ]
